extends VBoxContainer

## First part of each fact
var fact_start: Array = [
	"Brain worms like Parelaphostrongylus tenuis",
	"U.S. politics is shaped by the Constitution,",
	"The brain-eating amoeba Naegleria fowleri",
	"Brain worms rarely infect humans,",
	"U.S. politics is dominated by two parties,",
	"Brain-eating amoeba infections are rare,",
	"Brain worms spread through snails,",
	"The U.S. Supreme Court is the highest court,",
	"Brain-eating amoebas cause PAM,",
	"Brain worms like Angiostrongylus cantonensis",
	"U.S. politics relies on checks and balances,",
	"Brain-eating amoebas enter through the nose,",
	"Brain worms often infect deer,",
	"U.S. politics includes lobbying,",
	"Amoeba infections occur in warm climates,",
	"Brain worms have complex life cycles,",
	"The U.S. House of Representatives has 435 members,",
	"Brain-eating amoebas thrive in warm water,",
	"Brain worms don’t spread directly,",
	"U.S. politics allows for impeachment,",
	"Amoeba infections start with flu-like symptoms,",
	"Brain worms sometimes reach the spinal cord,",
	"U.S. politics uses the Electoral College,",
	"Brain-eating amoebas can’t survive in saltwater,",
	"Brain worms are found worldwide,",
	"U.S. politics is shaped by public opinion,",
	"Brain-eating amoebas multiply quickly,",
	"Brain worms in humans are rare,",
	"The U.S. Senate has 100 members,",
	"Amoeba infections are diagnosed through spinal fluid tests,"
]

## Middle part of each fact
var fact_mid: Array = [
	"can burrow into animal nervous systems,",
	"outlining government structure and rights,",
	"thrives in warm freshwater like lakes,",
	"but can cause confusion, headaches, and seizures,",
	"Democrats and Republicans,",
	"but survival is extremely rare,",
	"or contaminated vegetation,",
	"interpreting laws and shaping policies,",
	"a rare brain infection that destroys tissue,",
	"causes meningitis and neck stiffness,",
	"dividing power among three branches,",
	"reaching the brain within days,",
	"harmless to them but fatal to others,",
	"where groups influence lawmakers,",
	"mainly in southern states like Florida and Texas,",
	"involving snails, slugs, and mammals,",
	"with each state’s number based on population,",
	"especially in summer,",
	"but can spread through contaminated food,",
	"removing officials for misconduct,",
	"progressing rapidly to coma and seizures,",
	"causing paralysis and motor loss,",
	"where states get votes based on population,",
	"making oceans and chlorinated pools safe,",
	"with different species targeting different hosts,",
	"shaping election outcomes and policies,",
	"causing inflammation and brain damage,",
	"they mainly appear in Southeast Asia and the U.S",
	"with two senators from each state,",
	"but early detection is difficult,"
]

## Final part of each fact
var fact_end: Array = [
	"causing paralysis and death.",
	"and forming the foundation of U.S. politics.",
	"and poorly maintained swimming pools.",
	"and may lead to death.",
	"though third-party candidates also exist.",
	"with only a few known survivors.",
	"infecting animals that humans consume.",
	"making it a key force in U.S. politics.",
	"with most cases being fatal.",
	"and other severe neurological symptoms.",
	"to prevent abuses of power.",
	"causing rapid tissue destruction.",
	"making infections often deadly.",
	"often shaping key legislation.",
	"especially during warmer months.",
	"helping parasites complete their cycle.",
	"ensuring larger states have more influence.",
	"making hot environments riskier.",
	"if food isn't cooked properly.",
	"though it's rare and serious.",
	"with fatal outcomes in most cases.",
	"leading to permanent damage.",
	"giving bigger states more electoral votes.",
	"but freshwater lakes pose a risk.",
	"affecting animals in various regions.",
	"influencing campaigns and public policy.",
	"resulting in rapid cognitive decline.",
	"(especially in warmer climates).",
	"regardless of population size.",
	"due to symptoms resembling other illnesses."
]

var fact_sources = [
	"(Source: Cornell Vet)",
	"(Source: WhiteHouse.gov)",
	"(Source: CDC.gov)",
	"(Source: CDC.gov)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: Cornell Vet)",
	"(Source: SupremeCourt.gov)",
	"(Source: CDC.gov)",
	"(Source: CDC.gov)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: Cornell Vet)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: CDC.gov)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: CDC.gov)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: Cornell Vet)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: Cornell Vet)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)",
	"(Source: CDC.gov)",
	"(Source: USA.gov)",
	"(Source: CDC.gov)"
]
